name: tests-orders

on: 
  pull_request
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd GitTix/orders && npm install && npm run test:ci
   
