name: tests-auth

on: 
  pull_request:
    paths:
      - 'GitTix/auth/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd GitTix/auth && npm install && npm run test:ci
   
